In [1]:
using LinearAlgebra

In [2]:
#QR Algorithm implemented as a function on a matrix, configurable to allow iterating over any provided number of steps.
function QRAlgorithm(A,n)
  for i = 1:n
    Q,R = qr(A)
    A = R*Q
  end
  A
end

QRAlgorithm (generic function with 1 method)

In [3]:
#Function used to retrieve the diagonal entries of a matrix
function GetDiagonals(A)
  n = size(A)[1]
  output = zeros(n)
  for i = 1:n
    output[i] = A[i,i]
  end
  output
end
  

GetDiagonals (generic function with 1 method)

In [4]:
#Contruction of the provided matrix
A1 = [9 -7 -6 -13 -5; -7 5 -14 -8 -9; -6 -14 5 -5 -1; -13 -8 -5 13 5; -5 -9 -1 5 13]

5×5 Array{Int64,2}:
   9   -7   -6  -13  -5
  -7    5  -14   -8  -9
  -6  -14    5   -5  -1
 -13   -8   -5   13   5
  -5   -9   -1    5  13

In [5]:
#Displaying the eigenvalues for comparison to our results.
eigvals(A1)

5-element Array{Float64,1}:
 -20.188135264813763
   5.4436770493809945
  10.373436381368807
  19.814756669304543
  29.556265164759413

In [7]:
#Evaluating our approximation for the eigenvalues with only 20 iterations of the QR algorithm. I noticed that three of our values were incredibly accurate, while the other two were far off.
answer1 = QRAlgorithm(A1,20)
GetDiagonals(answer1)

5-element Array{Float64,1}:
  29.556252143009406
  15.263998719742208
 -15.637364293441745
  10.373436381273388
   5.443677049416727

In [8]:
#Displaying the full resulting matrix for observation. It is worth noting that the columns containing the worse approximations also have the non-diagonal entries furthest from zero.
answer1

5×5 Array{Float64,2}:
 29.5563        -0.00521345    -0.0240505    -5.00693e-8  -4.31144e-14
 -0.00521345    15.264        -12.7017       -1.03876e-5  -5.18237e-11
 -0.0240505    -12.7017       -15.6374       -4.24751e-5  -3.96636e-11
 -5.00693e-8    -1.03876e-5    -4.24751e-5   10.3734       1.32728e-5
 -4.05446e-14   -5.18186e-11   -3.96633e-11   1.32728e-5   5.44368

In [9]:
#The number of iterations were progressively increased. Contrary to my assumption, this made the values that were inaccurate even further from the correct value. However, our zero terms were slowly improving. In short, I set a bound for how far off our zero terms can be and tried to approach it. That took too long to slowly increment, so I went for the nuclear option and chose 1000. That seemed to work.
answer2 = QRAlgorithm(A1,1000)
GetDiagonals(answer2)

5-element Array{Float64,1}:
  29.556265164759363
 -20.188135264813496
  19.81475666930462
  10.373436381368819
   5.44367704938099

In [10]:
#Displaying the full resulting matrix for observation. Notice that the zero terms are much closer to zero. 
answer2

5×5 Array{Float64,2}:
 29.5563          9.87254e-15   -2.05256e-16    5.73448e-15   -2.57031e-15
  1.3967e-164   -20.1881        -1.26636e-6     7.12413e-15    2.07205e-15
  4.62949e-172   -1.26636e-6    19.8148         1.33206e-14   -4.74111e-15
  0.0             1.25439e-288   1.63296e-281  10.3734        -3.36138e-15
  0.0             0.0            0.0            4.93485e-280   5.44368